version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8086:8086
    depends_on:
      - postgres_db
    links:
      - postgres_db:database2
  postgres_db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: PWA
      POSTGRES_PASSWORD: postgres